### PR TITLE
Minor fix (line 90

### PR DESCRIPTION
**Pull request by kant**

### CODE REVIEW

**Comment by ivan-perevala** [comment]
You catch me) Thank you for correcting the description

**Comment by kant** [comment]
@ivan-perevala Your project is truly inspiring!

**Comment by ivan-perevala** [comment]
@kant Your activity on GitHub is truly inspiring!

A huge number of spelling corrections in the most diverse projects in almost all possible languages ​​(yes, yes, I understand that this process is automated for you and honestly it would be interesting to know your goal 😉)

**Comment by kant** [comment]
My pull request is not automated, so it's done by myself. It's a time-consuming task! This year, I hope, it will be more focused on those projects that like it most: blender tools and midi software...

**Pull request merged**
